name: android_device_info_demo
description: A new Flutter application.

version: 1.0.0

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.0.2
  intl: ^0.15.8
  permission_handler: ^3.0.0

  android_device_info:
    path: ../android_device_info

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/hush2.png
